[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = ["NEXT_PUBLIC_GOOGLE_CLIENT_ID"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
